services:
  db-tasks:
    image: postgres:15
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - task-network

  db-users:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - task-network

  service-tasks:
    build:
      context: ./serviceTasks
    depends_on:
      - db-tasks
    networks:
      - task-network

  service-users:
    build:
      context: ./serviceUsers
    depends_on:
      - db-users
    networks:
      - task-network

  api-gateway:
    build: ./APIGateway
    ports:
      - "8000:8080"
    depends_on:
      - service-users
      - service-tasks
    networks:
      - task-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
    - task-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    depends_on:
          - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - task-network

networks:
  task-network:
    driver: bridge